//! Generated SDK client adapter — bridges AppContext to the co-generated SDK.
//!
//! Auto-generated by @fern-api/cli-generator. Do not edit by hand.

#![allow(dead_code)]

use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

use fern_cli_sdk::error::CliError;
use fern_cli_sdk::openapi::AppContext;
use fern_cli_sdk::sdk_executor::{CliExecutor, SdkError, SdkRequestExecutor};

// ---------------------------------------------------------------------------
// Executor adapter: CliExecutor → SDK RequestExecutor
// ---------------------------------------------------------------------------

struct CliExecutorAdapter(Arc<CliExecutor>);

impl sikaru_sdk::RequestExecutor for CliExecutorAdapter {
    fn execute(
        &self,
        request: reqwest::Request,
    ) -> Pin<
        Box<
            dyn Future<Output = Result<reqwest::Response, Box<dyn std::error::Error + Send + Sync>>>
                + Send
                + '_,
        >,
    > {
        Box::pin(async move {
            SdkRequestExecutor::execute(&*self.0, request)
                .await
                .map_err(|e| Box::new(e) as Box<dyn std::error::Error + Send + Sync>)
        })
    }
}

// ---------------------------------------------------------------------------
// client — construct a fully-wired SDK root client
// ---------------------------------------------------------------------------

/// Build the SDK root client from the CLI's runtime context.
///
/// The returned client routes all HTTP through the CLI's executor, so
/// it inherits auth, retries, TLS, and global headers automatically.
pub fn client(ctx: &AppContext) -> sikaru_sdk::api::ApiClient {
    let executor = ctx.build_sdk_executor();
    let adapter = Arc::new(CliExecutorAdapter(executor));
    // Seed the base URL from the CLI's own resolution (--base-url / env >
    // spec base_url > server root). `ClientConfig::default()` carries an
    // empty `base_url` for any API that declares no environment, which made
    // every custom command fail on a relative URL before the executor ran.
    let config = sikaru_sdk::ClientConfig {
        base_url: ctx.effective_base_url(),
        ..Default::default()
    };
    let http_client = sikaru_sdk::HttpClient::with_executor(
        adapter as Arc<dyn sikaru_sdk::RequestExecutor>,
        config.clone(),
    );
    sikaru_sdk::api::ApiClient {
        config,
        activation: sikaru_sdk::api::ActivationClient { http_client: http_client.clone() },
        agent_imports: sikaru_sdk::api::AgentImportsClient { http_client: http_client.clone() },
        agents: sikaru_sdk::api::AgentsClient { http_client: http_client.clone() },
        changesets: sikaru_sdk::api::ChangesetsClient { http_client: http_client.clone() },
        compute_attachments: sikaru_sdk::api::ComputeAttachmentsClient { http_client: http_client.clone() },
        compute_operations: sikaru_sdk::api::ComputeOperationsClient { http_client: http_client.clone() },
        compute_workspaces: sikaru_sdk::api::ComputeWorkspacesClient { http_client: http_client.clone() },
        compute_credentials: sikaru_sdk::api::ComputeCredentialsClient { http_client: http_client.clone() },
        compute_environments: sikaru_sdk::api::ComputeEnvironmentsClient { http_client: http_client.clone() },
        compute_workers: sikaru_sdk::api::ComputeWorkersClient { http_client: http_client.clone() },
        connections: sikaru_sdk::api::ConnectionsClient { http_client: http_client.clone() },
        context_registry: sikaru_sdk::api::ContextRegistryClient { http_client: http_client.clone() },
        conversations: sikaru_sdk::api::ConversationsClient { http_client: http_client.clone() },
        deployments: sikaru_sdk::api::DeploymentsClient { http_client: http_client.clone() },
        environments: sikaru_sdk::api::EnvironmentsClient { http_client: http_client.clone() },
        eval_seeds: sikaru_sdk::api::EvalSeedsClient { http_client: http_client.clone() },
        evaluation_comparisons: sikaru_sdk::api::EvaluationComparisonsClient { http_client: http_client.clone() },
        evaluation_criteria: sikaru_sdk::api::EvaluationCriteriaClient { http_client: http_client.clone() },
        evaluation_jobs: sikaru_sdk::api::EvaluationJobsClient { http_client: http_client.clone() },
        evaluation_results: sikaru_sdk::api::EvaluationResultsClient { http_client: http_client.clone() },
        evaluator_runs: sikaru_sdk::api::EvaluatorRunsClient { http_client: http_client.clone() },
        execution_objectives: sikaru_sdk::api::ExecutionObjectivesClient { http_client: http_client.clone() },
        execution_sessions: sikaru_sdk::api::ExecutionSessionsClient { http_client: http_client.clone() },
        specialists: sikaru_sdk::api::SpecialistsClient { http_client: http_client.clone() },
        executions: sikaru_sdk::api::ExecutionsClient { http_client: http_client.clone() },
        feedback: sikaru_sdk::api::FeedbackClient { http_client: http_client.clone() },
        harness_versions: sikaru_sdk::api::HarnessVersionsClient { http_client: http_client.clone() },
        agent_budgets: sikaru_sdk::api::AgentBudgetsClient { http_client: http_client.clone() },
        harnesses: sikaru_sdk::api::HarnessesClient { http_client: http_client.clone() },
        runs: sikaru_sdk::api::RunsClient { http_client: http_client.clone() },
        import_sessions: sikaru_sdk::api::ImportSessionsClient { http_client: http_client.clone() },
        issue_clusters: sikaru_sdk::api::IssueClustersClient { http_client: http_client.clone() },
        judge_alignment: sikaru_sdk::api::JudgeAlignmentClient { http_client: http_client.clone() },
        managed_agents: sikaru_sdk::api::ManagedAgentsClient { http_client: http_client.clone() },
        memory_registry: sikaru_sdk::api::MemoryRegistryClient { http_client: http_client.clone() },
        model_gateway: sikaru_sdk::api::ModelGatewayClient { http_client: http_client.clone() },
        model_settings: sikaru_sdk::api::ModelSettingsClient { http_client: http_client.clone() },
        online_evaluations: sikaru_sdk::api::OnlineEvaluationsClient { http_client: http_client.clone() },
        release_watches: sikaru_sdk::api::ReleaseWatchesClient { http_client: http_client.clone() },
        retention_policies: sikaru_sdk::api::RetentionPoliciesClient { http_client: http_client.clone() },
        review_queue: sikaru_sdk::api::ReviewQueueClient { http_client: http_client.clone() },
        run_schedules: sikaru_sdk::api::RunSchedulesClient { http_client: http_client.clone() },
        run_webhooks: sikaru_sdk::api::RunWebhooksClient { http_client: http_client.clone() },
        sessions: sikaru_sdk::api::SessionsClient { http_client: http_client.clone() },
        tool_providers: sikaru_sdk::api::ToolProvidersClient { http_client: http_client.clone() },
        trace_import_connections: sikaru_sdk::api::TraceImportConnectionsClient { http_client: http_client.clone() },
        trace_imports: sikaru_sdk::api::TraceImportsClient { http_client: http_client.clone() },
        workflow_intents: sikaru_sdk::api::WorkflowIntentsClient { http_client: http_client.clone() },
        workflow_runs: sikaru_sdk::api::WorkflowRunsClient { http_client: http_client.clone() },
        workflows: sikaru_sdk::api::WorkflowsClient { http_client: http_client.clone() },
        trace_streams: sikaru_sdk::api::TraceStreamsClient { http_client: http_client.clone() },
    }
}

// ---------------------------------------------------------------------------
// block_on — async SDK call → sync handler result
// ---------------------------------------------------------------------------

/// Execute an async SDK operation from a synchronous custom-command handler.
///
/// Bridges the SDK's `ApiError` into the CLI's `CliError` so `?` works
/// naturally in handler bodies.
pub fn block_on<F, T>(future: F) -> Result<T, CliError>
where
    F: Future<Output = Result<T, sikaru_sdk::ApiError>>,
{
    tokio::task::block_in_place(|| {
        let handle = tokio::runtime::Handle::current();
        handle.block_on(future).map_err(convert_api_error)
    })
}

fn convert_api_error(e: sikaru_sdk::ApiError) -> CliError {
    match e {
        sikaru_sdk::ApiError::Http { status, message } => {
            fern_cli_sdk::error::api_error_from_body(status, &message)
        }
        sikaru_sdk::ApiError::Network(err) => {
            CliError::Other(anyhow::anyhow!("SDK network error: {err}"))
        }
        sikaru_sdk::ApiError::Executor(boxed) => match boxed.downcast::<SdkError>() {
            Ok(sdk_error) => sdk_error.into_cli_error(),
            Err(other) => CliError::Other(anyhow::anyhow!("SDK executor error: {other}")),
        },
        other => CliError::Other(anyhow::anyhow!("SDK error: {other}")),
    }
}
